version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - app_db
    networks:
      - leads

  app_db:
    image: postgres:latest
    restart: always 
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - leads

volumes:
  postgres_data:

networks:
  leads:
    driver: bridge